#!/usr/bin/env python

import common
import hashlib
import json
import os
import sys

DEBUG = True if os.getenv('DEBUG') == 'true' else False

def check_(instream):
    config = json.load(instream)
    response = []

    if DEBUG:
        print(config)

    envkey_value = config["source"].get('envkey')
    ignore = config["source"].get('ignore_vars', [])
    only_monitor = config["source"].get('only_monitor_vars', [])
    only_monitor_flag = True if len(only_monitor) > 0 else False

    vars = common.run_envkey_source_command(["--json"], {"ENVKEY": envkey_value})
    #remove ignored vars from tracking
    if not only_monitor_flag:
        for item in ignore:
            if item in vars:
                vars.pop(item)

    #remove everything except whats being asked to track
    filtered_vars = {}
    if only_monitor_flag:
        for item in only_monitor:
            filtered_vars[item] = vars[item]
    vars = filtered_vars

    # hash only vars we care about for tracking
    hash = hashlib.md5(json.dumps(vars, sort_keys=True).encode('utf-8')).hexdigest()

    if DEBUG:
        print("Vars:", vars)
        print("Hash:", hash)

    if 'version' in config:
        response.append(config['version'])

    response.append({"ref" : hash})

    return response


def main():
    print(json.dumps(check_(sys.stdin)))

if __name__ == '__main__':
    main()