#!/usr/bin/env python

import common
import envkey
import hashlib
import json
import os
import sys

DEBUG = True if os.getenv('DEBUG') == 'true' else False

def check_(instream):
    config = json.load(instream)
    response = []

    if DEBUG:
        print(config)

    envkey_value = config["source"].get('envkey')
    ignore = config["source"].get('ignore_vars', [])
    vars = envkey.fetch_env(envkey_value, cache_enabled=True)
    vars_with_ignorded_vars = common.remove_items_from_dict(vars,ignore)

    # hash only vars we care about for tracking
    hash = hashlib.md5(json.dumps(vars_with_ignorded_vars, sort_keys=True).encode('utf-8')).hexdigest()

    if DEBUG:
        print("Vars:", vars)
        print("Vars Ignore:", vars_with_ignorded_vars)
        print("Hash:", hash)

    if 'version' in config:
        response.append(config['version'])

    response.append({"ref" : hash})

    return response


def main():
    print(json.dumps(check_(sys.stdin)))

if __name__ == '__main__':
    main()