#!/usr/bin/env python

import common
import json
import hashlib
import os
import sys
import envkey

DEBUG = True if os.getenv('DEBUG') == 'true' else False

def in_(instream):
    sys_dir = sys.argv[1]
    env_file = os.path.join(sys_dir, '.env')
    config = json.load(instream)
    response = []

    if DEBUG:
        print(config)

    envkey_value = config["source"].get('envkey')
    ignore = config["source"].get('ignore_vars', [])
    vars = envkey.fetch_env(envkey_value, cache_enabled=True)
    vars_with_ignorded_vars = common.remove_items_from_dict(vars,ignore)

    # hash only vars we care about for tracking
    hash = hashlib.md5(json.dumps(vars_with_ignorded_vars, sort_keys=True).encode('utf-8')).hexdigest()

    if DEBUG:
        print("Vars:", vars)
        print("Vars Ignore:", vars_with_ignorded_vars)
        print("Hash:", hash)

    opened_file = open(env_file, "w")

    for k, v in vars.items():
        opened_file.write(str(k) + '='+ str(v) + '\n')

    opened_file.close()

    return {
        'version': { 'ref': hash}
    }

def main():
    print(json.dumps(in_(sys.stdin)))

if __name__ == '__main__':
    main()